### ISSUE TITLE
ellipsis placement differs per browser.

### ISSUE THREAD

**Issue by generalredneck** [MarcDiethelm/jQuery-Shorten#3] opened 2010-12-17 17:23 UTC
When trying to implement your plugin into my website, I am having positioning issues. It seems that positioning is respected in both chrome and IE, but not in FF. Here is a screenshot of all three lined up.
http://dl.dropbox.com/u/7177934/shorten_bugs/screenshot_172.png
In FF, it all depends on how the lettering falls whether or not it goes over or not. I have a overflow: hidden on that div so that's why you see only part of the ellipsis on some of the items in FF. I tried to change the code to use the Table way of measuring as opposed to canvas, and it worked exactly the same way. It does the same thing if I add width:203 (the width of the div's display area)

**Comment by MarcDiethelm** [comment] 2010-12-17 21:06
If I understand you correctly in the Firefox case the text IS truncated (as opposed to it's short enough to fit anyway) but the resulting text is still too long to fit?

Hm, you probably realize I can't reproduce this from a screenshot alone. Can you give me a link where I can examine the actual problem. You can send me a private message if a login is required.

**Comment by MarcDiethelm** [comment] 2010-12-20 16:48
Ok, I discovered a bug in the Canvas method while examining your use case. The font declaration had properties in the wrong order. Should be fixed with the latest commit.

Thanks for the bug report!

**Comment by generalredneck** [comment] 2010-12-20 18:54
Hell yeahs! That did it. Check it out.
http://dl.dropbox.com/u/7177934/shorten_bugs/screenshot_186.png

If I find anything else, I'll let you know... additionally, you should consider putting up a Donate button somewhere on one of your pages.

**Comment by MarcDiethelm** [comment] 2010-12-20 20:56
Cool, I'm glad it works as it's supposed to now. And thanks for the login.

I also just put up a means (two actually) for donations to the project on the demo/docu page:

http://web5.me/jquery/plugins/shorten/shorten.doc.html

**Closed as completed** 2010-12-21 00:48 UTC
